### ISSUE TITLE
Framework versioning is not valid for TestFlight

### ISSUE THREAD

**Issue by msworking** [dequelabs/axe-devtools-ios#10]
The current value for `CFBundleShortVersionString` of `3.3.0-770-c72d8d78` gets rejected by Apple for TestFlight submission as it is not in the standard semantic form. The value should simply be `3.2.0`

**Comment by karnett** [comment]
Thanks for reporting this issue @msworking  -- we have a fix in place for our next release estimated late March, early April. Please reach out to support.deque.com if you have any further questions.
