### ISSUE TITLE
Request to vend XCFramework as a release asset instead of committing to source control

### ISSUE THREAD

**Issue by master-nevi** [dequelabs/axe-devtools-ios#11]
Hello,
This is a request to have a ticket opened to consider releasing the iOS XCFrameworks as a Github release asset instead of merging directly into the https://github.com/dequelabs/axe-devtools-ios github repository.

Motivation: Cloning this project or installing it as a dependency takes a long time, and it’s likely due to every commit possessing a copy of a potentially large binary framework. Note that Swift Package Manager performs a deep clone of repositories, so over time, this library will cause longer and longer wait times when being cloned by SPM.

A common pattern is to instead upload these binaries with the release on Github. This way, the repository stays small and only the binary for a particular release is downloaded at one time. There are tools to automate this process also: https://github.com/marketplace/actions/swift-create-xcframework

Both cocoapods and SwiftPM support retrieving a zipped binary from a URL:

```swift
/// Package.swift
.binaryTarget(
            name: "axeDevTools",
            url: "https://github.com/dequelabs/axe-devtools-ios/releases/download/3.3.0/axeDevToolsUIKit.xcframework.zip",
            checksum: "The checksum of the ZIP archive that contains the XCFramework."
),
```

```ruby
#cocoapods
s.source = { :http => 'https://github.com/dequelabs/axe-devtools-ios/releases/download/3.3.0/axeDevToolsUIKit.xcframework.zip' }
s.ios.vendored_frameworks = 'axeDevToolsUIKit.xcframework'
```

**Comment by karnett** [comment]
Thanks for the suggestions @master-nevi . I've updated the latest releases from February to be releases with attached assets. 

We've got some changes coming down the road that we'd like to keep these in the same repo for. But I can promise it will be more simplified going forward. 

Please let us know if you continue seeing issues!
