### ISSUE TITLE
Invalid semantic version string 'UIKit_3.2.0'

### ISSUE THREAD

**Issue by master-nevi** [dequelabs/axe-devtools-ios#8]
**Please use semantic versioning as dictated by https://semver.org/** . Swift Package Manager is unable to parse versions in the format "UIKit_3.2.0" both in the Xcode `Package Dependencies` menu in the project settings and within a `Package.swift` file.

Your documentation states that one can use the version but in reality the only way to acquire your framework using SPM is by pinning to a particular Git commit or branch which is not ideal.

# Documentation
![Screen Shot 2023-01-20 at 4 09 01 PM](https://user-images.githubusercontent.com/987706/213827760-36dc82a0-2968-48c0-8eaa-473bc196f8e9.png)

# Via Package.swift
![Screen Shot 2023-01-20 at 4 03 11 PM](https://user-images.githubusercontent.com/987706/213828033-668e5c11-242d-4ba2-84ae-5fa3e6718fc0.png)
![Screen Shot 2023-01-20 at 4 02 23 PM 2](https://user-images.githubusercontent.com/987706/213828009-dd2799e4-b217-4168-9f11-311414930cdc.png)

# Via Xcode Project Settings
![Screen Shot 2023-01-20 at 4 10 47 PM 2](https://user-images.githubusercontent.com/987706/213827956-0e69dd3e-983e-4949-83de-88414c56996e.png)

**Comment by master-nevi** [comment]
If you ask me though, UIKit and XCUI should just be in separate repositories given their differences in purpose and release cycle.

**Comment by karnett** [comment]
Thanks for the suggestions @master-nevi . I've updated the latest releases from February to be releases with proper tagging. Please let us know if you continue seeing issues!
